sudo: required
services:
  - docker

before_install:
  - docker build -t jean84matias/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test


after_success:
  - docker build -t jean84matias/multi-client ./client
  - docker build -t jean84matias/multi-nginx ./nginx
  - docker build -t jean84matias/multi-server ./server
  - docker build -t jean84matias/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take thos images and push them to docker hub
  - docker push jean84matias/multi-client
  - docker push jean84matias/multi-nginx
  - docker push jean84matias/multi-server
  - docker push jean84matias/multi-worker

  

